# Generated by Django 4.1.6 on 2023-04-06 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("dateAdded", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="", help_text="Enter the product Name.", max_length=64
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="",
                        help_text="Enter the product Description.",
                        max_length=1000,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Enter product Price",
                        max_digits=10,
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(default=1, help_text="Enter product Quantity"),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Enter your Email.",
                        max_length=255,
                        unique=True,
                        verbose_name="email address",
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                (
                    "firstName",
                    models.CharField(
                        default="", help_text="Enter your Last Name.", max_length=64
                    ),
                ),
                (
                    "lastName",
                    models.CharField(
                        default="", help_text="Enter your First Name..", max_length=64
                    ),
                ),
                ("joinDate", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShoppingCart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "items",
                    models.ManyToManyField(
                        through="knockoffKing.CartItem", to="knockoffKing.product"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Select the User.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="knockoffKing.usermodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShippingInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "streetNumber",
                    models.CharField(
                        default="", help_text="Street Number", max_length=16
                    ),
                ),
                (
                    "streetName",
                    models.CharField(
                        default="", help_text="Street Name", max_length=64
                    ),
                ),
                ("city", models.CharField(default="", help_text="City", max_length=64)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("AL", "Alabama"),
                            ("AK", "Alaska"),
                            ("AZ", "Arizona       "),
                            ("AR", "Arkansas"),
                            ("CA", "California"),
                            ("CO", "Colorado      "),
                            ("CT", "Connecticut"),
                            ("DE", "Delaware"),
                            ("FL", "Florida       "),
                            ("GA", "Georgia"),
                            ("HI", "Hawaii"),
                            ("ID", "Idaho         "),
                            ("IL", "Illinois"),
                            ("IN", "Indiana"),
                            ("IA", "Iowa          "),
                            ("KS", "Kansas"),
                            ("KY", "Kentucky"),
                            ("LA", "Louisiana     "),
                            ("ME", "Maine"),
                            ("MD", "Maryland"),
                            ("MA", "Massachusetts "),
                            ("MI", "Michigan"),
                            ("MN", "Minnesota"),
                            ("MS", "Mississippi   "),
                            ("MO", "Missouri"),
                            ("MT", "Montana"),
                            ("NE", "Nebraska      "),
                            ("NV", "Nevada"),
                            ("NH", "New Hampshire"),
                            ("NJ", "New Jersey    "),
                            ("NM", "New Mexico"),
                            ("NY", "New York"),
                            ("NC", "North Carolina"),
                            ("OR", "North Dakota"),
                            ("PA", "Ohio"),
                            ("RI", "Oklahoma      "),
                            ("OR", "Oregon"),
                            ("PA", "Pennsylvania"),
                            ("RI", "Rhode Island  "),
                            ("SC", "South Carolina"),
                            ("SD", "South Dakota"),
                            ("TN", "Tennessee     "),
                            ("TX", "Texas"),
                            ("UT", "Utah"),
                            ("VT", "Vermont       "),
                            ("VA", "Virginia"),
                            ("WA", "Washington"),
                            ("WV", "West Virginia "),
                            ("WI", "Wisconsin"),
                            ("WY", "Wyoming"),
                        ],
                        default="AL",
                        help_text="State",
                        max_length=2,
                    ),
                ),
                ("zipCode", models.IntegerField(default="", help_text="Zip Code")),
                (
                    "shippingCost",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10000),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Select the User.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="knockoffKing.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Select the User.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="knockoffKing.usermodel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the Product.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="knockoffKing.seller",
            ),
        ),
        migrations.CreateModel(
            name="OrderDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                (
                    "subTotal",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Select the Product.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="knockoffKing.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("dateCreated", models.DateTimeField(auto_now_add=True)),
                ("dateShipped", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("01", "Order Placed"),
                            ("02", "Packaging"),
                            ("03", "Shipped"),
                            ("04", "In Transit"),
                            ("05", "Out for Delivery"),
                            ("06", "Delayed"),
                            ("07", "Delivered "),
                        ],
                        default="01",
                        help_text="Shipping Status",
                        max_length=2,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Select the Customer.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="knockoffKing.customer",
                    ),
                ),
                (
                    "shippingID",
                    models.ForeignKey(
                        help_text="Select the Shipping Info.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="knockoffKing.shippinginfo",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="customer",
            name="user",
            field=models.ForeignKey(
                help_text="Select the User.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="knockoffKing.usermodel",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="knockoffKing.product"
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="shoppingCart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="knockoffKing.shoppingcart",
            ),
        ),
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Select the User.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="knockoffKing.usermodel",
                    ),
                ),
            ],
        ),
    ]
