# Generated by Django 4.1.6 on 2023-04-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knockoffKing", "0003_alter_seller_options_alter_usermodel_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="seller",
            name="nameSlug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
