# Generated by Django 4.1.7 on 2023-04-13 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knockoffKing', '0005_orderitem_order_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('subTotal', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knockoffKing.order')),
                ('product', models.ForeignKey(help_text='Select the Product.', null=True, on_delete=django.db.models.deletion.CASCADE, to='knockoffKing.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knockoffKing.usermodel')),
            ],
        ),
        migrations.DeleteModel(
            name='OrderDetails',
        ),
    ]
