# Generated by Django 4.1.6 on 2023-04-29 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("knockoffKing", "0010_alter_seller_income"),
    ]

    operations = [
        migrations.AddField(
            model_name="seller",
            name="prevWithdraw",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="WithdrawHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="knockoffKing.seller",
                    ),
                ),
            ],
        ),
    ]
