# Generated by Django 4.1.6 on 2023-04-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knockoffKing", "0012_transactions_delete_withdrawhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactions",
            name="category",
            field=models.CharField(
                choices=[("deposit", "Deposit"), ("withdraw", "Withdraw")],
                default="deposit",
                max_length=10,
            ),
        ),
    ]
