# Generated by Django 4.1.6 on 2023-04-29 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knockoffKing", "0013_transactions_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="category",
            field=models.CharField(
                choices=[("Deposit", "Deposit"), ("Withdraw", "Withdraw")],
                default="Deposit",
                max_length=10,
            ),
        ),
    ]
