# Generated by Django 4.1.6 on 2023-04-30 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knockoffKing", "0014_alter_transactions_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="returnQuantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
