# Generated by Django 4.1.6 on 2023-04-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knockoffKing", "0015_orderitem_returnquantity_alter_orderitem_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shippinginfo",
            name="streetName",
        ),
        migrations.RemoveField(
            model_name="shippinginfo",
            name="streetNumber",
        ),
        migrations.AddField(
            model_name="shippinginfo",
            name="address1",
            field=models.CharField(
                db_column="streetNumber",
                default="",
                help_text="Address Line 1",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="shippinginfo",
            name="address2",
            field=models.CharField(
                db_column="streetName",
                default="",
                help_text="Address Line 2",
                max_length=64,
            ),
        ),
    ]
