# Generated by Django 4.1.6 on 2023-04-30 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("knockoffKing", "0016_remove_shippinginfo_streetname_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shippinginfo",
            name="customer",
        ),
        migrations.AddField(
            model_name="shippinginfo",
            name="user",
            field=models.ForeignKey(
                help_text="Select the User.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="knockoffKing.usermodel",
            ),
        ),
    ]
