# Generated by Django 4.1.6 on 2023-04-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knockoffKing", "0017_remove_shippinginfo_customer_shippinginfo_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippinginfo",
            name="zipCode",
            field=models.IntegerField(blank=True, help_text="Zip Code", null=True),
        ),
    ]
