# Generated by Django 4.1.6 on 2023-04-30 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("knockoffKing", "0019_alter_shippinginfo_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shippinginfo",
            name="shippingCost",
        ),
    ]
