# Generated by Django 4.1.6 on 2023-05-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knockoffKing", "0020_remove_shippinginfo_shippingcost"),
    ]

    operations = [
        migrations.AddField(
            model_name="seller",
            name="authenticated_by_admin",
            field=models.BooleanField(default=False, help_text="Authenticate Seller."),
        ),
    ]
